# Generated by Django 3.2.25 on 2024-09-13 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('maintenance_tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff.tariff', verbose_name='Тариф за содержание общего имущества')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер квартиры')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь квартиры')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='house.house')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ('number',),
            },
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('number', 'house'), name='unique_address'),
        ),
    ]
