# Generated by Django 3.2.25 on 2024-09-13 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Введите показания', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Показания счетчика')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата показаний')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_counters', to='house.flat', verbose_name='Квартира')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_counters', to='tariff.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Счетчик воды',
                'verbose_name_plural': 'Счетчики воды',
                'ordering': ('tariff',),
                'default_related_name': 'water_counters',
            },
        ),
    ]
