# Generated by Django 3.2.25 on 2024-09-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='Адресс')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Водоснабжение')),
                ('maintenance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Содержание общего имущества')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата показаний')),
                ('calculate_rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='rent.calculaterent', verbose_name='Расчет кварплаты')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='house.flat', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Квартплата',
                'verbose_name_plural': 'Квартплаты',
                'ordering': ('flat',),
                'default_related_name': 'rents',
            },
        ),
    ]
